language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer -n --no-ansi install --dev --prefer-source
script:
  - ./vendor/bin/phpunit --verbose -c tests/phpunit/phpunit.xml.travis
