language: php
php:
  - 5.4
  - 5.5
  - 5.6
branches:
  only:
    - develop
    - master
services:
  - mongodb
  - memcached
  - elasticsearch
before_install:
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install imagick-beta
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer -n --no-ansi install --dev --prefer-source
script:
  - ./vendor/bin/phpunit --verbose -c tests/phpunit/phpunit.xml.travis
  - ./vendor/bin/behat --strict --config tests/behat/behat.yml
